project_id = "mbbjmxubfeaudnhxmwqf"

[functions.sv-rewards-summary]
verify_jwt = false

[functions.fetch-acs-snapshot]
verify_jwt = false

[functions.upload-acs-snapshot]
verify_jwt = false

[functions.snapshot-scheduler]
verify_jwt = false
