project_id = "mbbjmxubfeaudnhxmwqf"

[functions.sv-rewards-summary]
verify_jwt = false

[functions.fetch-acs-snapshot]
verify_jwt = false

[functions.upload-acs-data]
verify_jwt = false

[functions.purge-acs-storage]
verify_jwt = false

[functions.get-governance-data]
verify_jwt = false

[functions.debug-governance]
verify_jwt = false